# Site settings.
title: No Such Meetup
url: "https://nosuchmeetup.pl/"
logo: "logo.png"

# Build settings.
theme: jekyll-theme-minimal

# Social media.
slack_url: https://join.slack.com/t/bsd-pl/shared_invite/enQtNTY5NTc2MDQ3OTU2LTE0ZjM5MWUyYzRlYmE2YzliZjIzYzk5MjM4MGViZDliMDI1MGUzNDA3NjdkODgzNGQxYTU0OTBkZWI0Y2E0MmE
mail_url: mailto:meetup@bsd-pl.org
facebook_url: https://www.facebook.com/pg/The-Polish-BSD-User-Group-2104511872897332
twitter_url: https://twitter.com/BSD_PL
youtube_url: https://www.youtube.com/channel/UCWvDQaEHSULuCIVOOM66nYA

# Link to the list of events.
registration_url: https://www.meetup.com/Polish-BSD-User-Group/events/
